# Generated by Django 3.0.8 on 2021-01-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XboxFriends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xuid', models.CharField(default=None, max_length=255, null=True)),
                ('state', models.CharField(default=None, max_length=255, null=True)),
                ('lastseen_titlename', models.CharField(default=None, max_length=255, null=True)),
                ('lastseen_timestamp', models.DateTimeField(default=None)),
                ('gamertag', models.CharField(default=None, max_length=255, null=True)),
                ('realname', models.CharField(default=None, max_length=255, null=True)),
                ('gamedisplayname', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
    ]
