# Generated by Django 3.0.8 on 2021-01-25 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xboxfriends',
            name='last_check',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
