# Generated by Django 3.0.8 on 2021-01-25 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addon', '0002_xboxfriends_last_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xboxfriends',
            name='lastseen_timestamp',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
